print("Music")
print("Music is listened by billions of people in this world but what makes it so special?")
print("1. Connection. I believe music often builds a connection from a person's mind to the mood or vibe the song is giving.")
print("2. Nostalgia. I highly believe that many different types of music makes a person instantly remember their past.")
print("3. Therapy. Music tends to heal a part of a person from within. Like they say, Music is therapy.")